server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dasdi_system
    username: root
    password: thanhdat123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 181619873625-bh9sdgsre067uoacdm7lq3e43a520ka9.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "https://api.dasdi.one/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1167844000836276
            clientSecret: c47edfe1cb78f2bf23b261ec85c5bd82
            redirectUri: "https://api.dasdi.one/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            userInfoUri: https://graph.facebook.com/me?fields=id,name,email,picture
  mail:
    host: smtp.gmail.com
    port: 587
    username: dasdi.system@gmail.com
    password: vslpklyigpqdymny
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

jwt:
  auth:
    secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - https://dasdi.one/oauth2/redirect

twilio:
  account_sid: ACf6d330f7967fcbba298f0b266ea262dc
  auth_token: 82b25483aa5a4668c697c5cfa01a1c28
  trial_number: +19259401736